version: '3.8'

services:
  benchmark:
    build: .
    image: ncb-phase1:latest
    container_name: ncb-phase1
    volumes:
      - ./notebooks:/app/notebooks  # Mount notebooks from workspace
      - ./results:/app/results                # For saving figures, metrics, logs (e.g., AUROC best)
      - Z:/nigeria_cxr_benchmark_phase1/workspace/data/preprocessed_dataset:/app/data:ro
      - ./requirements.lock.txt:/app/requirements.lock.txt
      - ./tests:/app/tests
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app                     
      - JUPYTER_ENABLE_LAB=yes               
    working_dir: /app                    
    command: >                                
      jupyter lab
      --ip=0.0.0.0
      --allow-root
      --no-browser
      --NotebookApp.token=''
      --NotebookApp.password=''

    # GPU support (requires NVIDIA Container Toolkit on host)
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]